#! /usr/bin/python3
# -*- coding: utf-8 -*-

#from sys import argv
#interface,vlan = argv[1:]


NAME = input('Enter device name: ').lower()
INTERFACE = input('Enter interface type and number: ').lower()
MODE = input('Enter interface mode (access/trunk ): ').lower()



fast_int = {'access':{'0/12':'10','0/14':'11','0/16':'17','0/17':'150'},
            'trunk':{'0/1':['add','10','20'],
                     '0/2':['only','11','30'],
                     '0/4':['del','17']} }

access_template = ['switchport mode access',
                  'switchport acess vlan {}',
                  'switchport nonegotiate',
                  'spanning-tree portfast',
                  'spanning-tree bpduguard enable']

trunk_template = ['switchport trunk encapsulation dot1q',
                  'switchport mode trunk',
                  'switchport trunk allowed vlan {}']

templates = {'access': access_template, 'trunk': trunk_template}
vlans_messages = {'access': 'Enter VLAN number: ', 'trunk': 'Enter allowed VLANs: '}

VLAN = input(vlans_messages[MODE]).lower()

print ('Конфигурация интерфейса {} в режиме {}:'.format(INTERFACE,MODE))

print ('interface {}'.format(INTERFACE))
print ('\n'.join(templates[MODE]).format(VLAN))

