#! /usr/bin/python
# search in list
import sys

num_list = [10, 2, 30, 100, 10, 50, 11, 30, 15, 7]
word_list = ['python', 'ruby', 'perl', 'ruby', 'perl', 'python', 'ruby', 'perl']

def find_li(list_name,param):
    index=list(reversed(list_name)).index(param)
    print index
    return len(list_name) - index -1

print find_li(num_list, 10)
