#! /usr/bin/python
import re

def parse_cfg(file_name):
	regex_str = "^ ip a.+[\d\.]+\s+[\d\.]+"
	regex_str2 = "^interface"
	regex_str3 = "^ ip a.+[\d\.]+\s+[\d\.]+ se.+"
	regex = re.compile(regex_str)
	regex2 = re.compile(regex_str2)
	regex3 = re.compile(regex_str3)
	list_out=[]
	d_keys=[]
	flag = False
	flag_IP = False
	with open(file_name, 'r') as f:
		sh_output=f.readlines()
		for line in sh_output:
			interface = re.findall(regex2, line)
			if interface:
				key=line[line.find(" "):].rstrip()
				flag = True	
				
			second_ip = re.findall(regex3, line)
			if second_ip:
				flag_IP = True				
			
			m = re.findall(regex, line)				
			if m and (flag == True or flag_IP == True):				
				if flag_IP:					
					list_out[-1].append(tuple(m[0].split(" ")[-2::]))					
				else:
					list_out.append([tuple(m[0].split(" ")[-2::])])
					d_keys.append(key)
					#print(list_out[-1])
					
				flag = False
				flag_IP = False
				
	return dict(zip(d_keys,list_out))
	#return list_out
				
if __name__ == "__main__":	
	from sys import argv
	file_name = argv[1]	
	print(parse_cfg(file_name))
	