#! /usr/bin/python3
# -*- coding: utf-8 -*-

#Задание 7.1
#
#Создать функцию, которая генерирует конфигурацию для access-портов.
#
#Параметр access ожидает, как аргумент, словарь access-портов, вида:
#    { 'FastEthernet0/12':10,
#      'FastEthernet0/14':11,
#      'FastEthernet0/16':17,
#      'FastEthernet0/17':150 }
#
#Функция должна возвращать список всех портов в режиме access
#с конфигурацией на основе шаблона access_template.
#
#В конце строк в списке не должно быть символа перевода строки.
#


def generate_access_config(access_dict):
	for i in access_dict.keys():
		print (i)
		for j in access_template:
			if j.endswith('access vlan'):
				print (j+" "+ str(access_dict[i]) )
				
			else:
				print (j)



access_dict = { 'FastEthernet0/12':10,
		'FastEthernet0/14':11,
		'FastEthernet0/16':17,
		'FastEthernet0/17':150 }				
				
access_template = ['switchport mode access',
		'switchport access vlan',
		'switchport nonegotiate',
		'spanning-tree portfast',
		'spanning-tree bpduguard enable']
				
generate_access_config(access_dict)