#! /usr/bin/python3

from sys import argv
# python 2.x
#IP = raw_input('Enter IP address in format 10.10.10.10/24: ')
#python 3.x
#IP = input('Enter IP address in format 10.10.10.10/24: ')

IP = argv[1]

IP_b =[]
mask = IP.split("/")[1]
mask_d=[]
IP = IP.split("/")[0].split(".")
for i in range(0, len(IP)) :
    IP[i]= '{:10}'.format(IP[i])
    IP_b.append('{:08b}'.format(int(IP[i],10)))

mask_b = list('{:0<32}'.format('1'*int(mask)))
for i in range(0,4):
    mask_b[i]= "".join(mask_b[i*8:(i+1)*8])
    mask_d.append('{:<10}'.format(int(mask_b[i],2)))
mask_b = mask_b[0:4]

print ("Host IP:")
print ("".join(IP))
print ("  ".join(IP_b))


#преобразование в IP сети
IP_b = list('{:0<32}'.format("".join(IP_b)[0:int(mask)]))
for i in range(0,4):
    IP_b[i] = "".join(IP_b[i*8:(i+1)*8])
    IP[i] = '{:<10}'.format(int(str(IP_b[i]),2))
IP_b=IP_b[0:4]


print ("\n"  "Network:")
print ("".join(IP))
print ("  ".join(IP_b))

print ("\n" "Mask:")
print ("/{}".format(mask))
print ("".join(mask_d))
print ("  ".join(mask_b))
