#! /usr/bin/python3

from sys import argv

ignore = ['duplex', 'alias', 'Current configuration']

def contains_words(text, words_list):
    for word in words_list:
        if text.find(word) != -1:
            return True
    return False 


f_out = open("config_sw1_cleared.txt", 'w+')	
with open(argv[1], 'r') as f:
	for command in f:
		command = command.rstrip()
		if contains_words(command, ignore):
			continue
		else:
			f_out.write(command + '\n')
f_out.close()