#! /usr/bin/python3

from t_8_2 import parse_cdp_neighbors
from draw_network_graph import draw_topology

from sys import argv

cdp_n = argv[1]

with open(cdp_n , 'r') as f:
        cdp_neighbors = f.read()


draw_topology(parse_cdp_neighbors(cdp_neighbors))


	
	
