#! /usr/bin/python
import re

def return_match(file_name,regex_str):
	regex = re.compile(regex_str)
	list_out=[]
	with open(file_name, 'r') as f:
		sh_output=f.readlines()
		for line in sh_output:			
			m = re.findall(regex, line)				
			if m:						
				list_out.append(m[0].lstrip())
	return list_out
				
if __name__ == "__main__":	
	from sys import argv
	file_name = argv[1]
	regex_str = " [\d\.]+"
	print(return_match(file_name,regex_str))
	