#! /usr/bin/python
import re

def parse_cfg(file_name):
	regex_str = "^ ip a.+[\d\.]+\s+[\d\.]+"	
	regex = re.compile(regex_str)
	list_out=[]
	with open(file_name, 'r') as f:
		sh_output=f.readlines()
		for line in sh_output:	
			#line = line.strip()
			m = re.findall(regex, line)				
			if m:						
				list_out.append(tuple(m[0].split(" ")[-2::]))				
				
	return list_out
				
if __name__ == "__main__":	
	from sys import argv
	file_name = argv[1]	
	print(parse_cfg(file_name))
	